version: '3'
services:
  api_nginx:
    image: nginx
    env_file:
      - nginx.env 
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mainpage:/var/mainpage
      - ./trainpage:/var/trainpage
    ports:
      - "80:80"
      - "81:81"
