version: '3'
services:
  database:
    image: "postgres:12.3" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/home/ec2-user/postgresql/data/ # persist data even if container shuts downxO
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
     - "5432:5432"
volumes:
  database-data: # named volumes can be managed easier using docker-compose
